/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcadeIndexRouteImport } from './routes/arcade.index'
import { Route as ArcadePlayGameIdRouteImport } from './routes/arcade.play.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeIndexRoute = ArcadeIndexRouteImport.update({
  id: '/arcade/',
  path: '/arcade/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadePlayGameIdRoute = ArcadePlayGameIdRouteImport.update({
  id: '/arcade/play/$gameId',
  path: '/arcade/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arcade/': typeof ArcadeIndexRoute
  '/arcade/play/$gameId': typeof ArcadePlayGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arcade': typeof ArcadeIndexRoute
  '/arcade/play/$gameId': typeof ArcadePlayGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arcade/': typeof ArcadeIndexRoute
  '/arcade/play/$gameId': typeof ArcadePlayGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arcade/' | '/arcade/play/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arcade' | '/arcade/play/$gameId'
  id: '__root__' | '/' | '/arcade/' | '/arcade/play/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArcadeIndexRoute: typeof ArcadeIndexRoute
  ArcadePlayGameIdRoute: typeof ArcadePlayGameIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade/': {
      id: '/arcade/'
      path: '/arcade'
      fullPath: '/arcade/'
      preLoaderRoute: typeof ArcadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade/play/$gameId': {
      id: '/arcade/play/$gameId'
      path: '/arcade/play/$gameId'
      fullPath: '/arcade/play/$gameId'
      preLoaderRoute: typeof ArcadePlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArcadeIndexRoute: ArcadeIndexRoute,
  ArcadePlayGameIdRoute: ArcadePlayGameIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
