/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArcadeIndexRouteImport } from './routes/arcade/index'
import { Route as PlayGameIdRouteImport } from './routes/play.$gameId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeIndexRoute = ArcadeIndexRouteImport.update({
  id: '/arcade/',
  path: '/arcade/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayGameIdRoute = PlayGameIdRouteImport.update({
  id: '/play/$gameId',
  path: '/play/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/arcade/': typeof ArcadeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/arcade': typeof ArcadeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play/$gameId': typeof PlayGameIdRoute
  '/arcade/': typeof ArcadeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/play/$gameId' | '/arcade/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/play/$gameId' | '/arcade'
  id: '__root__' | '/' | '/play/$gameId' | '/arcade/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayGameIdRoute: typeof PlayGameIdRoute
  ArcadeIndexRoute: typeof ArcadeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade/': {
      id: '/arcade/'
      path: '/arcade'
      fullPath: '/arcade/'
      preLoaderRoute: typeof ArcadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$gameId': {
      id: '/play/$gameId'
      path: '/play/$gameId'
      fullPath: '/play/$gameId'
      preLoaderRoute: typeof PlayGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayGameIdRoute: PlayGameIdRoute,
  ArcadeIndexRoute: ArcadeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
